#!/bin/bash
# just a quick script to not go to the trouble
echo "//# generated by script on "$(date)"" > ./icons.jsx
echo " " >> ./icons.jsx

# imports
for file in ./*.svg 
do
    basename=$(basename ${file})
    filename=${basename%.*}
    filename="${filename^}"
    echo "import "$filename" from './$basename';" >> ./icons.jsx
    
done

echo " " >> ./icons.jsx
echo "import { SvgIcon } from '@mui/material';" >> ./icons.jsx
echo " " >> ./icons.jsx
echo " " >> ./icons.jsx

# list of icons
echo "export const AirportIconsNames = [" >> ./icons.jsx
for file in ./*.svg 
do
    basename=$(basename ${file})
    filename=${basename%.*}
    filename="${filename^}"
    echo "'${filename}Icon',">> ./icons.jsx
done
echo "]" >> ./icons.jsx
echo " " >> ./icons.jsx

# React wrapper
echo "export const AirportIcons = (props) => {" >> ./icons.jsx
echo "switch (props.type){" >> ./icons.jsx

for file in ./*.svg 
do
    basename=$(basename ${file})
    filename=${basename%.*}
    filename="${filename^}"
    echo "case '${filename}Icon':" >> ./icons.jsx
    echo "return(<${filename}Icon sx={props.sx} color={props.color}/>)" >> ./icons.jsx
done
echo "}" >> ./icons.jsx
echo "};" >> ./icons.jsx
echo " " >> ./icons.jsx

# svg icons
for file in ./*.svg 
do
    basename=$(basename ${file})
    filename=${basename%.*}
    filename="${filename^}"
    echo "export const ${filename}Icon = (props) => (" >> ./icons.jsx
    echo "<SvgIcon sx={props.sx} color={props.color} component={$filename} inheritViewBox />" >> ./icons.jsx
    echo ")" >> ./icons.jsx
    echo " " >> ./icons.jsx
    
done

