//# generated by script on Fri May 12 17:05:53 JST 2023
 
import Baggagecarousel from './baggagecarousel.svg';
import Baggageclaim from './baggageclaim.svg';
import Customs from './customs.svg';
import Flightschedule from './flightschedule.svg';
import Immigration from './immigration.svg';
import Kiosk from './kiosk.svg';
import Passenger from './passenger.svg';
import Passportcontrol from './passportcontrol.svg';
import Security from './security.svg';
import Securityguard from './securityguard.svg';
import Waitingarea from './waitingarea.svg';
import Waitingpassenger from './waitingpassenger.svg';
 
import { Box, SvgIcon } from '@mui/material';
import IconButton from '@mui/material/IconButton';
 
 
export const BaggagecarouselIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Baggagecarousel} inheritViewBox />
);
 
export const BaggageclaimIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Baggageclaim} inheritViewBox />
);
 
export const CustomsIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Customs} inheritViewBox />
);
 
export const FlightscheduleIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Flightschedule} inheritViewBox />
);
 
export const ImmigrationIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Immigration} inheritViewBox />
);
 
export const KioskIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Kiosk} inheritViewBox />
);
 
export const PassengerIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Passenger} inheritViewBox />
);
 
export const PassportcontrolIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Passportcontrol} inheritViewBox />
);
 
export const SecurityIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Security} inheritViewBox />
);
 
export const SecurityguardIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Securityguard} inheritViewBox />
);
 
export const WaitingareaIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Waitingarea} inheritViewBox />
);
 
export const WaitingpassengerIcon = (props) => (
<SvgIcon sx={props.sx} color='secondary' component={Waitingpassenger} inheritViewBox />
);
 
