//# generated by script on Fri May 12 17:30:51 JST 2023
import Baggagecarousel from "./baggagecarousel.svg";
import Baggageclaim from "./baggageclaim.svg";
import Customs from "./customs.svg";
import Flightschedule from "./flightschedule.svg";
import Immigration from "./immigration.svg";
import Kiosk from "./kiosk.svg";
import Passenger from "./passenger.svg";
import Passportcontrol from "./passportcontrol.svg";
import Security from "./security.svg";
import Securityguard from "./securityguard.svg";
import Waitingarea from "./waitingarea.svg";
import Waitingpassenger from "./waitingpassenger.svg";

import { Box, SvgIcon } from "@mui/material";
import IconButton from "@mui/material/IconButton";

export const AirportIcons = (props) => {
  return airportIconObject[props.type];
};

const airportIconObject = {
  BaggagecarouselIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Baggagecarousel}
      inheritViewBox
    />
  ),

  BaggageclaimIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Baggageclaim}
      inheritViewBox
    />
  ),

  CustomsIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Customs}
      inheritViewBox
    />
  ),

  FlightscheduleIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Flightschedule}
      inheritViewBox
    />
  ),

  ImmigrationIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Immigration}
      inheritViewBox
    />
  ),

  KioskIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Kiosk}
      inheritViewBox
    />
  ),

  PassengerIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Passenger}
      inheritViewBox
    />
  ),

  PassportcontrolIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Passportcontrol}
      inheritViewBox
    />
  ),

  SecurityIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Security}
      inheritViewBox
    />
  ),

  SecurityguardIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Securityguard}
      inheritViewBox
    />
  ),

  WaitingareaIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Waitingarea}
      inheritViewBox
    />
  ),

  WaitingpassengerIcon: (props) => (
    <SvgIcon
      sx={props.sx}
      color={props.color}
      component={Waitingpassenger}
      inheritViewBox
    />
  ),
};
