//# generated by script on Fri May 12 19:43:47 JST 2023

import Baggagecarousel from "./baggagecarousel.svg";
import Baggageclaim from "./baggageclaim.svg";
import Customs from "./customs.svg";
import Flightschedule from "./flightschedule.svg";
import Immigration from "./immigration.svg";
import Kiosk from "./kiosk.svg";
import Passenger from "./passenger.svg";
import Passportcontrol from "./passportcontrol.svg";
import Security from "./security.svg";
import Securityguard from "./securityguard.svg";
import Waitingarea from "./waitingarea.svg";
import Waitingpassenger from "./waitingpassenger.svg";

import { SvgIcon } from "@mui/material";

export const AirportIconsNames = [
  "BaggagecarouselIcon",
  "BaggageclaimIcon",
  "CustomsIcon",
  "FlightscheduleIcon",
  "ImmigrationIcon",
  "KioskIcon",
  "PassengerIcon",
  "PassportcontrolIcon",
  "SecurityIcon",
  "SecurityguardIcon",
  "WaitingareaIcon",
  "WaitingpassengerIcon",
];

export const AirportIcons = (props) => {
  switch (props.type) {
    case "BaggagecarouselIcon":
      return <BaggagecarouselIcon sx={props.sx} color={props.color} />;
    case "BaggageclaimIcon":
      return <BaggageclaimIcon sx={props.sx} color={props.color} />;
    case "CustomsIcon":
      return <CustomsIcon sx={props.sx} color={props.color} />;
    case "FlightscheduleIcon":
      return <FlightscheduleIcon sx={props.sx} color={props.color} />;
    case "ImmigrationIcon":
      return <ImmigrationIcon sx={props.sx} color={props.color} />;
    case "KioskIcon":
      return <KioskIcon sx={props.sx} color={props.color} />;
    case "PassengerIcon":
      return <PassengerIcon sx={props.sx} color={props.color} />;
    case "PassportcontrolIcon":
      return <PassportcontrolIcon sx={props.sx} color={props.color} />;
    case "SecurityIcon":
      return <SecurityIcon sx={props.sx} color={props.color} />;
    case "SecurityguardIcon":
      return <SecurityguardIcon sx={props.sx} color={props.color} />;
    case "WaitingareaIcon":
      return <WaitingareaIcon sx={props.sx} color={props.color} />;
    case "WaitingpassengerIcon":
      return <WaitingpassengerIcon sx={props.sx} color={props.color} />;
  }
};

export const BaggagecarouselIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Baggagecarousel}
    inheritViewBox
  />
);

export const BaggageclaimIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Baggageclaim}
    inheritViewBox
  />
);

export const CustomsIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Customs}
    inheritViewBox
  />
);

export const FlightscheduleIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Flightschedule}
    inheritViewBox
  />
);

export const ImmigrationIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Immigration}
    inheritViewBox
  />
);

export const KioskIcon = (props) => (
  <SvgIcon sx={props.sx} color={props.color} component={Kiosk} inheritViewBox />
);

export const PassengerIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Passenger}
    inheritViewBox
  />
);

export const PassportcontrolIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Passportcontrol}
    inheritViewBox
  />
);

export const SecurityIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Security}
    inheritViewBox
  />
);

export const SecurityguardIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Securityguard}
    inheritViewBox
  />
);

export const WaitingareaIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Waitingarea}
    inheritViewBox
  />
);

export const WaitingpassengerIcon = (props) => (
  <SvgIcon
    sx={props.sx}
    color={props.color}
    component={Waitingpassenger}
    inheritViewBox
  />
);
