#!/bin/bash
# just a quick script to not go to the trouble

echo "//# generated by script on "$(date)"" > ./icons.jsx
echo " " >> ./icons.jsx

for file in ./*.svg 
do
    basename=$(basename ${file})
    filename=${basename%.*}
    filename="${filename^}"
    echo "import "$filename" from './$basename';" >> ./icons.jsx
    
done

echo " " >> ./icons.jsx
echo "import { Box, SvgIcon } from '@mui/material';" >> ./icons.jsx
echo "import IconButton from '@mui/material/IconButton';" >>./icons.jsx
echo " " >> ./icons.jsx
echo " " >> ./icons.jsx


for file in ./*.svg 
do
    basename=$(basename ${file})
    filename=${basename%.*}
    filename="${filename^}"
    echo "export const ${filename}Icon = (props) => (" >> ./icons.jsx
    echo "<SvgIcon sx={props.sx} color='secondary' component={$filename} inheritViewBox />" >> ./icons.jsx
    echo ");" >> ./icons.jsx
    echo " " >> ./icons.jsx
    
done
